### ISSUE TITLE
Jason.load geeft error in trelloattachments

### ISSUE THREAD

**Issue by cjvanzwol** [roytje88/JupyterNotebook_for_trello#2]
-------------------------------------------------------------------
JSONDecodeError                   Traceback (most recent call last)
<ipython-input-19-5c3a250f1721> in <module>
      5 f.close()
      6 
----> 7 allboards = json.loads(json.dumps(requests.get("https://api.trello.com/1/members/me/boards?key="+api_key+"&token="+api_token).json()))
      8 printprint(allboards)

/data/user/0/ru.iiec.pydroid3/files/aarch64-linux-android/lib/python3.7/site-packages/requests/models.py in json(self, **kwargs)
    895                     # used.
    896                     pass
--> 897         return complexjson.loads(self.text, **kwargs)
    898 
    899     @property

/data/user/0/ru.iiec.pydroid3/files/aarch64-linux-android/lib/python3.7/json/__init__.py in loads(s, encoding, cls, object_hook, parse_float, parse_int, parse_constant, object_pairs_hook, **kw)
    346             parse_int is None and parse_float is None and
    347             parse_constant is None and object_pairs_hook is None and not kw):
--> 348         return _default_decoder.decode(s)
    349     if cls is None:
    350         cls = JSONDecoder

/data/user/0/ru.iiec.pydroid3/files/aarch64-linux-android/lib/python3.7/json/decoder.py in decode(self, s, _w)
    335 
    336         """
--> 337         obj, end = self.raw_decode(s, idx=_w(s, 0).end())
    338         end = _w(s, end).end()
    339         if end != len(s):

/data/user/0/ru.iiec.pydroid3/files/aarch64-linux-android/lib/python3.7/json/decoder.py in raw_decode(self, s, idx)
    353             obj, end = self.scan_once(s, idx)
    354         except StopIteration as err:
--> 355             raise JSONDecodeError("Expecting value", s, err.value) from None
    356         return obj, end

JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by roytje88** [comment]
De volgende libraries geven geen fout als je ze importeert?

`import json
import requests`

**Comment by cjvanzwol** [comment]
Nee, importeren gaat prima.

Op di 14 jan. 2020 07:10 schreef roytje88 <notifications@github.com>:

**Comment by cjvanzwol** [comment]
Het was een probleem met mijn token. Ik heb het hersteld en nu werkt dat weer.
